name: regulation_evolution
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - cmake=3.16.3
  - python=3.9
  - pip
  - pip:
    - colorir==1.4.0
    - colormath==3.0.0
    - ete3==3.1.2
    - ipython==8.7.0
    - kaleido==0.2.1
    - numpy==1.22.4
    - plotly==5.11.0
    - enlighten==1.11.1
    - pandas==1.5.3
    - pyqt5==5.15.7
    - networkx==2.8.8
    - matplotlib
