name: regulation_evolution
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - nlohmann_json==3.11.2
  - pip:
    - colorir==1.3.14
    - colormath==3.0.0
    - ete3==3.1.2
    - ipython==8.7.0
    - kaleido==0.2.1
    - matplotlib-inline==0.1.6
    - numpy==1.22.4
    - plotly==5.11.0
